---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go-web-app
  template:
    metadata:
      labels:
        name: go-web-app
    spec:
      containers:
      - name: application
        image: shiluanzzz/gin-test
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8989
---
apiVersion: v1
kind: Service
metadata:
  name: go-web-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 8989
    targetPort: 8989 
  selector:
    name: go-web-app

# ---
# #ingress
# kind: Ingress
# apiVersion: v1
# metadata:
#   name: go-web-app
# spec:
#   rules:
#   - host: localhost
#     http:
#       paths:
#       - path:
#         backend:
#           serviceName: go-web-app # 这里对应着service 的 名字
#           servicePort: 8989 # 对应着需要映射的service的端口
